# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

from Manger.StreamyManger import StreamyManger
from Messages.AudioConfig import AudioConfig
from Messages.StreamyFormRequest import StreamyFormRequest
from Messages.VideoConfig import VideoConfig
import threading

class Ui_Form(object):

    def create_query(self, stream_url, server_url, server_key, tab_index,
                     vps_type, radio_btn1, radio_btn2, radio_btn3,
                     radio_btn4, aps_type, sample_rate, block_size):

        stream_url = stream_url
        rtmp_server_url = server_url
        rtmp_server_key = server_key

        width = None
        height = None

        if radio_btn1 is True:
            width = 256
            height = 144
        if radio_btn2 is True:
            width = 426
            height = 240
        if radio_btn3 is True:
            width = 640
            height = 360
        if radio_btn4 is True:
            width = 854
            height = 480

        audio_config = None
        video_config = None

        if vps_type == 0:
            vps_type = 'selfie'
        elif vps_type == 1:
            vps_type = 'motion'

        if aps_type == 0:
            aps_type = 'threshold'
        elif aps_type == 1:
            aps_type = 'psd'
        elif aps_type == 2:
            aps_type = 'demucs'
        print(stream_url)
        print(rtmp_server_url)
        print(rtmp_server_key)
        print(audio_config)
        print(aps_type)
        print(vps_type)

        if tab_index == 0:
            print('video')
            video_config = VideoConfig(width=width, height=height)
        if tab_index == 1:
            print('audio')
            audio_config = AudioConfig(sample_rate=sample_rate, block_size=block_size)

        request_example = StreamyFormRequest(
            stream_url=stream_url,
            rtmp_server_url=rtmp_server_url,
            rtmp_server_key=rtmp_server_key,
            audio_config=audio_config,
            video_config=video_config,
            secure_mode=False,
            aps_type=aps_type,
            vps_type=vps_type)

        return request_example

    def wrong_message(self, stream_url, server_url, server_key, tab_index, sample_rate, block_size):

        message = None

        if stream_url == '':
            message = "Enter Stream URL"
        elif server_url == '':
            message = "Enter Server URL"
        elif server_key == '':
            message = "Enter Server Key"
        elif tab_index == 1 and sample_rate == '':
            message = "Enter Sample Rate"
        elif tab_index == 1 and block_size == '':
            message = "Enter Block Size"

        if message is None:
            return True

        q = QtWidgets.QMessageBox.warning(self.Form, "Warning", message)
        return False

    def Click(self):

        stream_url = self.streamUrl.text()
        server_url = self.serverUrl.text()
        server_key = self.serverKey.text()
        tab_index = self.tab.currentIndex()

        ### video settings ###
        vps_type = self.comboVpsType.currentIndex()
        radio_btn1 = self.radioButton.isChecked()
        radio_btn2 = self.radioButton_2.isChecked()
        radio_btn3 = self.radioButton_3.isChecked()
        radio_btn4 = self.radioButton_4.isChecked()

        ### Audio settings ###
        aps_type = self.comboApsType.currentIndex()
        sample_rate = self.sampleRate.text()
        block_size = self.blockSize.text()

        check = self.wrong_message(stream_url, server_url, server_key, tab_index, sample_rate, block_size)

        if check is True:
            request_example = self.create_query(stream_url, server_url, server_key, tab_index,
                                                vps_type, radio_btn1, radio_btn2, radio_btn3,
                                                radio_btn4, aps_type, sample_rate, block_size)

            print(request_example)
            print('video configgg:' ,request_example.video_config)
            print('audio configgg:' ,request_example.audio_config)
            manger = StreamyManger()
            self.Form.close()
            #x = threading.Thread(target=manger.serve_request, args=(request_example,))
            #x.start()
            manger.serve_request(request=request_example)

    def setupUi(self, Form):
        self.Form = Form

        Form.setObjectName("Form")
        Form.resize(957, 588)
        Form.setStyleSheet("QToolTip\n"
                           "{\n"
                           "     border: 1px solid black;\n"
                           "     background-color: #ffa02f;\n"
                           "     padding: 1px;\n"
                           "     border-radius: 3px;\n"
                           "     opacity: 100;\n"
                           "}\n"
                           "\n"
                           "QWidget\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #323232;\n"
                           "}\n"
                           "\n"
                           "QTreeView, QListView\n"
                           "{\n"
                           "    background-color: silver;\n"
                           "    margin-left: 5px;\n"
                           "}\n"
                           "\n"
                           "QWidget:item:hover\n"
                           "{\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
                           "    color: #000000;\n"
                           "}\n"
                           "\n"
                           "QWidget:item:selected\n"
                           "{\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item\n"
                           "{\n"
                           "    background: transparent;\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item:selected\n"
                           "{\n"
                           "    background: transparent;\n"
                           "    border: 1px solid #ffaa00;\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item:pressed\n"
                           "{\n"
                           "    background: #444;\n"
                           "    border: 1px solid #000;\n"
                           "    background-color: QLinearGradient(\n"
                           "        x1:0, y1:0,\n"
                           "        x2:0, y2:1,\n"
                           "        stop:1 #212121,\n"
                           "        stop:0.4 #343434/*,\n"
                           "        stop:0.2 #343434,\n"
                           "        stop:0.1 #ffaa00*/\n"
                           "    );\n"
                           "    margin-bottom:-1px;\n"
                           "    padding-bottom:1px;\n"
                           "}\n"
                           "\n"
                           "QMenu\n"
                           "{\n"
                           "    border: 1px solid #000;\n"
                           "}\n"
                           "\n"
                           "QMenu::item\n"
                           "{\n"
                           "    padding: 2px 20px 2px 20px;\n"
                           "}\n"
                           "\n"
                           "QMenu::item:selected\n"
                           "{\n"
                           "    color: #000000;\n"
                           "}\n"
                           "\n"
                           "QWidget:disabled\n"
                           "{\n"
                           "    color: #808080;\n"
                           "    background-color: #323232;\n"
                           "}\n"
                           "\n"
                           "QAbstractItemView\n"
                           "{\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
                           "}\n"
                           "\n"
                           "QWidget:focus\n"
                           "{\n"
                           "    /*border: 1px solid darkgray;*/\n"
                           "}\n"
                           "\n"
                           "QLineEdit\n"
                           "{\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
                           "    padding: 1px;\n"
                           "    border-style: solid;\n"
                           "    border: 1px solid #1e1e1e;\n"
                           "    border-radius: 5;\n"
                           "}\n"
                           "\n"
                           "QPushButton\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                           "    border-width: 1px;\n"
                           "    border-color: #1e1e1e;\n"
                           "    border-style: solid;\n"
                           "    border-radius: 6;\n"
                           "    padding: 3px;\n"
                           "    font-size: 12px;\n"
                           "    padding-left: 5px;\n"
                           "    padding-right: 5px;\n"
                           "    min-width: 40px;\n"
                           "}\n"
                           "\n"
                           "QPushButton:pressed\n"
                           "{\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                           "}\n"
                           "\n"
                           "QComboBox\n"
                           "{\n"
                           "    selection-background-color: #ffaa00;\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
                           "    border-style: solid;\n"
                           "    border: 1px solid #1e1e1e;\n"
                           "    border-radius: 5;\n"
                           "}\n"
                           "\n"
                           "QComboBox:hover,QPushButton:hover\n"
                           "{\n"
                           "    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QComboBox:on\n"
                           "{\n"
                           "    padding-top: 3px;\n"
                           "    padding-left: 4px;\n"
                           "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                           "    selection-background-color: #ffaa00;\n"
                           "}\n"
                           "\n"
                           "QComboBox QAbstractItemView\n"
                           "{\n"
                           "    border: 2px solid darkgray;\n"
                           "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "}\n"
                           "\n"
                           "QComboBox::drop-down\n"
                           "{\n"
                           "     subcontrol-origin: padding;\n"
                           "     subcontrol-position: top right;\n"
                           "     width: 15px;\n"
                           "\n"
                           "     border-left-width: 0px;\n"
                           "     border-left-color: darkgray;\n"
                           "     border-left-style: solid; /* just a single line */\n"
                           "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                           "     border-bottom-right-radius: 3px;\n"
                           " }\n"
                           "\n"
                           "QComboBox::down-arrow\n"
                           "{\n"
                           "     image: url(:/dark_orange/img/down_arrow.png);\n"
                           "}\n"
                           "\n"
                           "QGroupBox\n"
                           "{\n"
                           "    border: 1px solid darkgray;\n"
                           "    margin-top: 10px;\n"
                           "}\n"
                           "\n"
                           "QGroupBox:focus\n"
                           "{\n"
                           "    border: 1px solid darkgray;\n"
                           "}\n"
                           "\n"
                           "QTextEdit:focus\n"
                           "{\n"
                           "    border: 1px solid darkgray;\n"
                           "}\n"
                           "\n"
                           "QScrollBar:horizontal {\n"
                           "     border: 1px solid #222222;\n"
                           "     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                           "     height: 7px;\n"
                           "     margin: 0px 16px 0 16px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::handle:horizontal\n"
                           "{\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                           "      min-height: 20px;\n"
                           "      border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-line:horizontal {\n"
                           "      border: 1px solid #1b1b19;\n"
                           "      border-radius: 2px;\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "      width: 14px;\n"
                           "      subcontrol-position: right;\n"
                           "      subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::sub-line:horizontal {\n"
                           "      border: 1px solid #1b1b19;\n"
                           "      border-radius: 2px;\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "      width: 14px;\n"
                           "     subcontrol-position: left;\n"
                           "     subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
                           "{\n"
                           "      border: 1px solid black;\n"
                           "      width: 1px;\n"
                           "      height: 1px;\n"
                           "      background: white;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                           "{\n"
                           "      background: none;\n"
                           "}\n"
                           "\n"
                           "QScrollBar:vertical\n"
                           "{\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                           "      width: 7px;\n"
                           "      margin: 16px 0 16px 0;\n"
                           "      border: 1px solid #222222;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::handle:vertical\n"
                           "{\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                           "      min-height: 20px;\n"
                           "      border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::add-line:vertical\n"
                           "{\n"
                           "      border: 1px solid #1b1b19;\n"
                           "      border-radius: 2px;\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                           "      height: 14px;\n"
                           "      subcontrol-position: bottom;\n"
                           "      subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::sub-line:vertical\n"
                           "{\n"
                           "      border: 1px solid #1b1b19;\n"
                           "      border-radius: 2px;\n"
                           "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
                           "      height: 14px;\n"
                           "      subcontrol-position: top;\n"
                           "      subcontrol-origin: margin;\n"
                           "}\n"
                           "\n"
                           "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                           "{\n"
                           "      border: 1px solid black;\n"
                           "      width: 1px;\n"
                           "      height: 1px;\n"
                           "      background: white;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                           "{\n"
                           "      background: none;\n"
                           "}\n"
                           "\n"
                           "QTextEdit\n"
                           "{\n"
                           "    background-color: #242424;\n"
                           "}\n"
                           "\n"
                           "QPlainTextEdit\n"
                           "{\n"
                           "    background-color: #242424;\n"
                           "}\n"
                           "\n"
                           "QHeaderView::section\n"
                           "{\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    border: 1px solid #6c6c6c;\n"
                           "}\n"
                           "\n"
                           "QCheckBox:disabled\n"
                           "{\n"
                           "color: #414141;\n"
                           "}\n"
                           "\n"
                           "QDockWidget::title\n"
                           "{\n"
                           "    text-align: center;\n"
                           "    spacing: 3px; /* spacing between items in the tool bar */\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button, QDockWidget::float-button\n"
                           "{\n"
                           "    text-align: center;\n"
                           "    spacing: 1px; /* spacing between items in the tool bar */\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
                           "{\n"
                           "    background: #242424;\n"
                           "}\n"
                           "\n"
                           "QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
                           "{\n"
                           "    padding: 1px -1px -1px 1px;\n"
                           "}\n"
                           "\n"
                           "QMainWindow::separator\n"
                           "{\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    border: 1px solid #4c4c4c;\n"
                           "    spacing: 3px; /* spacing between items in the tool bar */\n"
                           "}\n"
                           "\n"
                           "QMainWindow::separator:hover\n"
                           "{\n"
                           "\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    border: 1px solid #6c6c6c;\n"
                           "    spacing: 3px; /* spacing between items in the tool bar */\n"
                           "}\n"
                           "\n"
                           "QToolBar::handle\n"
                           "{\n"
                           "     spacing: 3px; /* spacing between items in the tool bar */\n"
                           "     background: url(:/dark_orange/img/handle.png);\n"
                           "}\n"
                           "\n"
                           "QMenu::separator\n"
                           "{\n"
                           "    height: 2px;\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
                           "    color: white;\n"
                           "    padding-left: 4px;\n"
                           "    margin-left: 10px;\n"
                           "    margin-right: 5px;\n"
                           "}\n"
                           "\n"
                           "QProgressBar\n"
                           "{\n"
                           "    border: 2px solid grey;\n"
                           "    border-radius: 5px;\n"
                           "    text-align: center;\n"
                           "}\n"
                           "\n"
                           "QProgressBar::chunk\n"
                           "{\n"
                           "    background-color: #d7801a;\n"
                           "    width: 2.15px;\n"
                           "    margin: 0.5px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab {\n"
                           "    color: #b1b1b1;\n"
                           "    border: 1px solid #444;\n"
                           "    border-bottom-style: none;\n"
                           "    background-color: #323232;\n"
                           "    padding-left: 10px;\n"
                           "    padding-right: 10px;\n"
                           "    padding-top: 3px;\n"
                           "    padding-bottom: 2px;\n"
                           "    margin-right: -1px;\n"
                           "}\n"
                           "\n"
                           "QTabWidget::pane {\n"
                           "    border: 1px solid #444;\n"
                           "    top: 1px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:last\n"
                           "{\n"
                           "    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
                           "    border-top-right-radius: 3px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:first:!selected\n"
                           "{\n"
                           " margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
                           "\n"
                           "\n"
                           "    border-top-left-radius: 3px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:!selected\n"
                           "{\n"
                           "    color: #b1b1b1;\n"
                           "    border-bottom-style: solid;\n"
                           "    margin-top: 3px;\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:selected\n"
                           "{\n"
                           "    border-top-left-radius: 3px;\n"
                           "    border-top-right-radius: 3px;\n"
                           "    margin-bottom: 0px;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab:!selected:hover\n"
                           "{\n"
                           "    /*border-top: 2px solid #ffaa00;\n"
                           "    padding-bottom: 3px;*/\n"
                           "    border-top-left-radius: 3px;\n"
                           "    border-top-right-radius: 3px;\n"
                           "    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #323232;\n"
                           "    border: 1px solid #b1b1b1;\n"
                           "    border-radius: 6px;\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:checked\n"
                           "{\n"
                           "    background-color: qradialgradient(\n"
                           "        cx: 0.5, cy: 0.5,\n"
                           "        fx: 0.5, fy: 0.5,\n"
                           "        radius: 1.0,\n"
                           "        stop: 0.25 #ffaa00,\n"
                           "        stop: 0.3 #323232\n"
                           "    );\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator{\n"
                           "    color: #b1b1b1;\n"
                           "    background-color: #323232;\n"
                           "    border: 1px solid #b1b1b1;\n"
                           "    width: 9px;\n"
                           "    height: 9px;\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator\n"
                           "{\n"
                           "    border-radius: 6px;\n"
                           "}\n"
                           "\n"
                           "QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
                           "{\n"
                           "    border: 1px solid #ffaa00;\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:checked\n"
                           "{\n"
                           "    image:url(:/dark_orange/img/checkbox.png);\n"
                           "}\n"
                           "\n"
                           "QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
                           "{\n"
                           "    border: 1px solid #444;\n"
                           "}\n"
                           "\n"
                           "\n"
                           "QSlider::groove:horizontal {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    height: 8px;\n"
                           "    background: #201F1F;\n"
                           "    margin: 2px 0;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::handle:horizontal {\n"
                           "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
                           "      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 14px;\n"
                           "    height: 14px;\n"
                           "    margin: -4px 0;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::groove:vertical {\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 8px;\n"
                           "    background: #201F1F;\n"
                           "    margin: 0 0px;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QSlider::handle:vertical {\n"
                           "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
                           "      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
                           "    border: 1px solid #3A3939;\n"
                           "    width: 14px;\n"
                           "    height: 14px;\n"
                           "    margin: 0 -4px;\n"
                           "    border-radius: 2px;\n"
                           "}\n"
                           "\n"
                           "QAbstractSpinBox {\n"
                           "    padding-top: 2px;\n"
                           "    padding-bottom: 2px;\n"
                           "    border: 1px solid darkgray;\n"
                           "\n"
                           "    border-radius: 2px;\n"
                           "    min-width: 50px;\n"
                           "}\n"
                           "")
        self.streamUrl = QtWidgets.QLineEdit(Form)
        self.streamUrl.setGeometry(QtCore.QRect(10, 40, 301, 41))
        self.streamUrl.setObjectName("streamUrl")
        self.tab = QtWidgets.QTabWidget(Form)
        self.tab.setGeometry(QtCore.QRect(330, 40, 621, 541))
        self.tab.setObjectName("tab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.comboVpsType = QtWidgets.QComboBox(self.tab1)
        self.comboVpsType.setGeometry(QtCore.QRect(140, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboVpsType.setFont(font)
        self.comboVpsType.setObjectName("comboVpsType")
        self.comboVpsType.addItem("")
        self.comboVpsType.addItem("")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(30, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.tab1)
        self.radioButton.setGeometry(QtCore.QRect(30, 170, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 200, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 230, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 260, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.tab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.comboApsType = QtWidgets.QComboBox(self.tab2)
        self.comboApsType.setGeometry(QtCore.QRect(140, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboApsType.setFont(font)
        self.comboApsType.setObjectName("comboApsType")
        self.comboApsType.addItem("")
        self.comboApsType.addItem("")
        self.comboApsType.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.sampleRate = QtWidgets.QLineEdit(self.tab2)
        self.sampleRate.setGeometry(QtCore.QRect(140, 140, 301, 41))
        self.sampleRate.setObjectName("sampleRate")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        self.label_5.setGeometry(QtCore.QRect(30, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.blockSize = QtWidgets.QLineEdit(self.tab2)
        self.blockSize.setGeometry(QtCore.QRect(140, 220, 301, 41))
        self.blockSize.setObjectName("blockSize")
        self.tab.addTab(self.tab2, "")
        self.serverKey = QtWidgets.QLineEdit(Form)
        self.serverKey.setGeometry(QtCore.QRect(10, 140, 301, 41))
        self.serverKey.setText("")
        self.serverKey.setObjectName("serverKey")
        self.serverUrl = QtWidgets.QLineEdit(Form)
        self.serverUrl.setGeometry(QtCore.QRect(10, 90, 301, 41))
        self.serverUrl.setObjectName("serverUrl")
        self.startStream = QtWidgets.QPushButton(Form)
        self.startStream.setGeometry(QtCore.QRect(90, 270, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.startStream.setFont(font)
        self.startStream.setObjectName("startStream")
        self.startStream.clicked.connect(self.Click)

        self.retranslateUi(Form)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.streamUrl.setPlaceholderText(_translate("Form", "  Enter Stream URL"))
        self.comboVpsType.setItemText(0, _translate("Form", " Selfie"))
        self.comboVpsType.setItemText(1, _translate("Form", " Motion"))
        self.label.setText(_translate("Form", "VPS Type"))
        self.label_3.setText(_translate("Form", "Frame Dimensions"))
        self.radioButton.setText(_translate("Form", "144p"))
        self.radioButton_2.setText(_translate("Form", "240p"))
        self.radioButton_3.setText(_translate("Form", "360p"))
        self.radioButton_4.setText(_translate("Form", "480p"))
        self.tab.setTabText(self.tab.indexOf(self.tab1), _translate("Form", "Video Streaming Settings"))
        self.comboApsType.setItemText(0, _translate("Form", " Threshold"))
        self.comboApsType.setItemText(1, _translate("Form", " Psd"))
        self.comboApsType.setItemText(2, _translate("Form", " Demucs"))
        self.label_2.setText(_translate("Form", "APS Type"))
        self.label_4.setText(_translate("Form", "Sample Rate"))
        self.sampleRate.setPlaceholderText(_translate("Form", "  Enter Sample Rate"))
        self.label_5.setText(_translate("Form", "Block Size"))
        self.blockSize.setPlaceholderText(_translate("Form", "  Enter Block Size"))
        self.tab.setTabText(self.tab.indexOf(self.tab2), _translate("Form", "Audio Streaming Setting"))
        self.serverKey.setPlaceholderText(_translate("Form", "  Enter RTMP Server Key"))
        self.serverUrl.setPlaceholderText(_translate("Form", "  Enter RTMP Server URL"))
        self.startStream.setText(_translate("Form", "Start Stream"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
